"""
BSA 2023 Section 63 — Evidence Certificate Generator (Phase A3).

Generates a PDF certificate with:
    Part A (auto-filled): case ID, hash algorithm, hash value, timestamp,
        system identity.
    Part B (blank): expert name, designation, date, signature — never
        auto-filled; this is the legally load-bearing human attestation.

Uses fpdf2 for PDF generation.
"""

from fpdf import FPDF
from datetime import datetime

from app.models import CaseOut


# ---------------------------------------------------------------------------
# Certificate PDF builder
# ---------------------------------------------------------------------------

class _CertificatePDF(FPDF):
    """Custom PDF layout for BSA 2023 §63 evidence certificate."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "EVIDENCE CERTIFICATE", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.cell(
            0, 6,
            "Under Section 63, Bharatiya Sakshya Adhiniyam, 2023",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.ln(4)
        # Divider line
        self.set_draw_color(100, 100, 100)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 10,
            f"Generated by CyberIntel Forensic Intelligence System | Page {self.page_no()}",
            align="C",
        )


def generate_certificate(case: CaseOut) -> bytes:
    """
    Generate a BSA 2023 §63 evidence certificate PDF for the given case.

    Returns:
        Raw PDF bytes ready to be served as an HTTP response.
    """
    pdf = _CertificatePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)

    generated_at = datetime.utcnow().isoformat() + "Z"

    # -----------------------------------------------------------------------
    # PART A — Electronic Record Details (auto-filled)
    # -----------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "PART A - Electronic Record Details", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    _add_field(pdf, "Case ID", case.case_id)
    _add_field(pdf, "Hash Algorithm", "SHA-256")
    _add_field(pdf, "Hash Value", case.sha256_hash)
    _add_field(pdf, "Submitted At", case.submitted_at)
    _add_field(pdf, "Certificate Generated At", generated_at)
    _add_field(pdf, "Submitted By", case.submitted_by)
    _add_field(
        pdf, "System Identity",
        "CyberIntel Forensic Intelligence System v0.2.0"
    )
    _add_field(pdf, "Processing Status", case.status)

    # Entity summary
    if case.entity_counts:
        entity_summary = ", ".join(
            f"{etype}: {count}" for etype, count in case.entity_counts.items()
        )
        _add_field(pdf, "Entities Extracted", entity_summary)

    _add_field(pdf, "Total Entities", str(sum(case.entity_counts.values())))

    pdf.ln(4)

    # Certification statement
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(
        0, 5,
        "I hereby certify that the electronic record identified above was "
        "produced by the CyberIntel system during the ordinary course of "
        "its automated processing activities. The SHA-256 hash was computed "
        "at the point of ingestion to ensure tamper-evidence and chain-of-"
        "custody compliance. The system was operating properly at the time "
        "of the creation of the electronic record.",
    )
    pdf.ln(4)

    # Part A completion marker
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(0, 128, 0)
    pdf.cell(0, 6, "[Part A: AUTO-FILLED - COMPLETE]", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # Divider
    pdf.set_draw_color(100, 100, 100)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # -----------------------------------------------------------------------
    # PART B — Certifying Expert Attestation (blank — human must sign)
    # -----------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(
        0, 8,
        "PART B - Certificate of Responsible Person (Section 63(4))",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(
        0, 5,
        "To be completed by the person occupying a responsible official "
        "position in relation to the operation of the relevant device or "
        "the management of the relevant activities, as required under "
        "Section 63(4) of the Bharatiya Sakshya Adhiniyam, 2023.",
    )
    pdf.ln(4)

    # Blank signature fields
    _add_signature_field(pdf, "Name of Certifying Expert")
    _add_signature_field(pdf, "Designation / Rank")
    _add_signature_field(pdf, "Organization / Unit")
    _add_signature_field(pdf, "Date of Certification")
    pdf.ln(8)
    _add_signature_field(pdf, "Signature", line_width=80)

    pdf.ln(6)

    # Part B completion marker
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(180, 0, 0)
    pdf.cell(
        0, 6,
        "[Part B: REQUIRES MANUAL COMPLETION BY AUTHORIZED EXPERT]",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)

    return bytes(pdf.output())


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _add_field(pdf: FPDF, label: str, value: str) -> None:
    """Render a label: value row."""
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(55, 6, f"{label}:", new_x="RIGHT")
    pdf.set_font("Courier", "", 9)
    pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")


def _add_signature_field(
    pdf: FPDF, label: str, line_width: int = 120
) -> None:
    """Render a label with an underline for handwritten input."""
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(55, 8, f"{label}:")
    x = pdf.get_x()
    y = pdf.get_y() + 7
    pdf.line(x, y, x + line_width, y)
    pdf.ln(8)
